name: Lotto Buy Bot (로또 구매봇)

on: [push]
# on:
#   schedule:
#     - cron: "50 23 * * 5" # UST 기준의 크론. UST 23:50 는 KST 08:50

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Python packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('builds.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install python packages
        run: |
          pip install -r builds.txt

      - name: Install ubuntu package
        run: |
          sudo apt-get install fonts-unfonts-core
          sudo apt-get install fonts-unfonts-extra
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add
          sudo apt-get install google-chrome-stable
          wget https://chromedriver.storage.googleapis.com/100.0.4896.20/chromedriver_linux64.zip
          unzip ./chromedriver_linux64.zip

      - name: Run for buying Lotto!
        run: |
          python ./buy_lotto.py ${{secrets.USER_ID}} ${{secrets.USER_PW}} ${{secrets.SLACK_BOT_TOKEN}} ${{secrets.SLACK_CHANNEL}} 1
